---
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    
params:
  district_lea_id: '1'
  year: 2019
  
---

```{r setup, include=FALSE, results = 'hide'}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

nces_number <- '051068001566' # north little rock

years <- 2000:2019
devtools::load_all()
```

```{r loadData, results = 'hide', include = FALSE}

data_sources_to_import <- c('enrollment race', 'enrollment lep', 'state assessments')

# get all Urban Institute Education Data Portal API data
ed_data <- get_all_educationdata(nces_number, years, data_sources_to_import)

school_directory <- ed_data$directory$data %>%
  dplyr::mutate(dplyr::across(school_name:city_location, ~stringr::str_to_title(.x)))

# get state to extract district and census tract shape files
state_abb <- school_directory$state_location

# get district shapefile
district_shapefile <- tigris::school_districts(state = state_abb, cb = FALSE) %>%
  # filter for district
  dplyr::filter(GEOID == school_directory$leaid)

school_name <- school_directory$school_name[1]

dashboard_title <- stringr::str_c(school_name, " Landscape Analysis")

yr <- school_directory$year[[1]]

district_year <- glue::glue("{yr} - {yr + 1}")
```

<script>
document.querySelector(".navbar-header > span.navbar-brand").innerHTML = "`r dashboard_title`";
</script> 


District Overview {data-orientation=rows}
=====================================   

Row
-----------------------------------------------------------------------

### Grades in School

```{r}
school_grades <- glue::glue("{school_directory$lowest_grade_offered} - {school_directory$highest_grade_offered}")

flexdashboard::valueBox(school_grades, icon = "fa-school")
```

### School Enrollment<br>`r district_year`

```{r}
school_enrollment <- school_directory$enrollment[[1]] %>%
  as.numeric() %>%
  scales::comma()

flexdashboard::valueBox(school_enrollment, icon = "fa-child")
```

### FTE Teachers at School<br>`r district_year`

```{r}
school_teachers <- school_directory$teachers_fte[[1]] %>%
  as.numeric() %>%
  scales::comma()

flexdashboard::valueBox(school_teachers, icon = "fa-chalkboard-teacher")
```

### Free or Reduced Lunch Students<br>`r district_year`

```{r}
free_reduced_lunch <- school_directory$free_or_reduced_price_lunch[[1]] %>%
  as.numeric() %>%
  scales::comma()

perc_free_reduced <- scales::percent(school_directory$perc_free_reduced_lunch[[1]])

free_reduced_lunch <- glue::glue("{free_reduced_lunch} ({perc_free_reduced})")

flexdashboard::valueBox(free_reduced_lunch, icon = "fa-utensils")
```

Row
-------------------------------------

### District Map {data-width=700}

```{r include = FALSE}
# must create the map in a different code chunk than the chunk it is printed in
# this is because sf prints a statement in one of the commands and the only
# way to suppress the statement is the include the header include = FALSE
# but, this header prevents the map from showing as well
district_map <- leaflet_district_schools(district_shapefile, school_directory)
``` 

```{r}
district_map
```

### Cities in District {data-width=200}

```{r citiesTable, include = FALSE, results = 'hide'}
pop_colname <- glue::glue("**City Pop.<br>{max(years)}**")

cities_table <- table_cities_in_single_district(district_shapefile, state = state_abb, year = max(years)) %>%
  cities_in_district()
```

```{r}
cities_table
```

School Demographics {data-orientation=rows}
=====================================  

Row {data-height=400}
-----------------------------------------------------------------------

### Total Enrollment by Year

```{r}
total_enrollment <- ed_data$enrollment_race$data %>%
  dplyr::filter(race == 'Total')

school_year_x_label <- 'School Year'

tooltip_html <- create_html_tooltip('year', '', 'total_enrollment') %>%
  stringr::str_remove("[(]") %>%
  stringr::str_remove("[)]")

highcharter::hchart(total_enrollment, "line", highcharter::hcaes(x = year, y = total_enrollment))  %>%
  custom_hc_tooltip(tooltip_html) %>%
  add_title_axis_labels(
    plt_title = glue::glue("{school_name}\nStudent Enrollment by School Year"),
    plt_x_label = school_year_x_label,
    plt_y_label = "Enrollment"
  )
```

Row {data-height=400}
-----------------------------------------------------------------------

### Enrollment by Race

```{r}
initial_race_order <- c('Black, African-American', 'Hispanic / Latinx', 'White')

race_enrollment <- ed_data$enrollment_race$data %>%
  dplyr::filter(race != 'Total')

race_enrollment$race <- relevel_race(race_enrollment$race)

tooltip_html <- create_html_tooltip('race', 'perc_cleaned', 'total_enrollment')

race_enrollment %>%
  dplyr::arrange(dplyr::desc(year), race) %>%
  create_school_demo_linechart(
    x_col = 'year', y_col = 'perc_enrollment', group_col = 'race', 
    tool_tip_html = tooltip_html, 
    plt_title = "Enrollment by Race",
    x_var_title = school_year_x_label,
    y_var_title = "Percentage Enrollment by Race"
  )
```
