---
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    
params:
  nces_num: '1'
  years: 2000:2020
  state_abb: 'NC'
  grades: 6:12
  org_level: 'schools'
  
---

```{r setup, include=FALSE, results = 'hide'}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

library(glue)
library(forcats)
library(stringr)
library(tigris)
library(purrr)
library(dplyr)
library(highcharter)
library(schoolreportr)
library(flexdashboard)
library(gt)

# Persistance Prep ---------------------
nces_num <- '360117206648'
state_abb <- 'NY'
years <- 2010:2020
grades <- c('k', '1', '2', '3', '4')
org_level <- 'schools'
```

```{r loadData, results = 'hide', include = FALSE}
# years data is available
saipe_years <- schoolreportr:::data_years_available('saipe')
ccd_years <- schoolreportr:::data_years_available('ccd')

state_fips <- schoolreportr:::state_fips_code(state_abb)

school_directory <- schoolreportr:::get_ccd_directory(org_level, nces_num, max(ccd_years))

# you should only have one district. Produce error if there are more than one.
if (length(unique(school_directory$leaid)) > 1) stop("All schools must be in the same school district")

district_leaid_number <- unique(school_directory$leaid)

school_names <- paste0(school_directory$school_name, collapse = " & ") %>%
  str_to_title()

school_enrollment <- schoolreportr:::get_ccd_enrollment(org_level, nces_num, years, grades)

district_poverty <- schoolreportr:::get_district_in_poverty(district_leaid_number, max(saipe_years))

# for grades 9-12 in state assessments by school, they are lumped together as 9th grade
assessment_grades <- unique(ifelse(grades > 9, 9, grades))

dashboard_title <- str_c(school_names, " Landscape Analysis")
```

```{r results = 'hide', include = FALSE}
max_ccd_year <- max(school_directory$year)
ccd_year <- glue("{max_ccd_year}-{max_ccd_year}")

lowest_grade <- grades[1]
highest_grade <- grades[length(grades)]
grade_span <- glue("{lowest_grade}-{highest_grade}") %>%
  str_to_title()
```

<script>
document.querySelector(".navbar-header > span.navbar-brand").innerHTML = "`r dashboard_title`";
</script> 

School Demographics {data-orientation=rows}
=====================================  

Row {data-height=400}
-----------------------------------------------------------------------

### Total Enrollment by Year

```{r}
total_enrollment <- school_enrollment %>%
  filter(race == 'Total')

school_year_x_label <- 'School Year'

plt_tooltip <- paste0("<b>", school_names, ":</b>  {point.y:.0f} students")

hchart(total_enrollment, "line", hcaes(x = school_year_both, y = enrollment),
                    tooltip = list(pointFormat = plt_tooltip))  %>%
  schoolreportr:::add_title_axis_labels(
    plt_title = glue("{school_names}\nStudent Enrollment by School Year (grades {grade_span})"),
    plt_x_label = school_year_x_label,
    plt_y_label = glue("Enrollment in grades {grade_span}")
  )
```

Row {data-height=400}
-----------------------------------------------------------------------

### Enrollment by Race and Year

```{r}
race_y_var_title <- glue("Percentage Enrollment by Race (grades {grade_span})")

school_enrollment %>%
  schoolreportr:::clean_enrollment_by_race() %>%
  schoolreportr:::hc_plot_grouped_line(
    x_col = 'school_year_both', y_col = 'percent_race', group_col = 'race', 
    plt_title = NULL, 
    x_var_title = school_year_x_label, y_var_title = race_y_var_title,
    y_percentage = TRUE
  ) %>%
  schoolreportr:::custom_hc_tooltip(create_html_tooltip('race', 'percent_race_clean', 'enrollment'))
```

Row
-----------------------------------------------------------------------

```{r}

free_lunch <- glue("{school_directory$free_lunch} ({scales::percent(school_directory$perc_free_lunch)})")

misc_info <- tribble(
  ~item,                                          ~value,
  "Number of FTE teachers:  ",                     as.character(school_directory$teachers_fte),
  "Number of students receiving free lunch:  ",    free_lunch
)

assessment_data <- tribble(
  ~subject,              ~pers_prep_avg,  ~state_avg,
  "ELA 3rd Grade",     "18% (7 of 39)",   "28%",
  "Math 3rd Grade",    "10% (4 of 40)",   "24%"
)
```

### Misc. SY 2020-2021 Data

```{r}
misc_info %>%
  gt() %>%
    tab_style(
      style = list(cell_text(weight = "bold")),
      locations = cells_body(columns = item)
    ) %>%
  tab_options(column_labels.hidden = TRUE)
```

### ELA and Math Assessment Data

```{r}
assessment_data %>%
  gt() %>%
    tab_style(
      style = list(cell_text(weight = "bold")),
      locations = cells_body(columns = subject)
    ) %>%
  cols_label(
    subject = "Subject",
    pers_prep_avg = "Persistence Prep % Proficient (2020-2021)",
    state_avg = "NY % Proficient (2019-2020)"
  )
```
